import bs4
exampleFile = open('example.html')
exampleSoup = bs4.BeautifulSoup(exampleFile.read(), 'html.parser')
p_elems = exampleSoup.select('p')
str(p_elems[0])
print(p_elems[0])
p_elems[0].getText()
print(p_elems[0].getText())
str(p_elems[1])
print(str(p_elems[1]))
p_elems[1].getText()
print(p_elems[1].getText())
str(p_elems[2])
print(str(p_elems[2]))
p_elems[2].getText()
print(p_elems[2].getText())
